apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-logs-manager-sa
  namespace: k8s-logs-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-logs-manager-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-logs-manager-binding
subjects:
  - kind: ServiceAccount
    name: k8s-logs-manager-sa
    namespace: k8s-logs-manager
roleRef:
  kind: ClusterRole
  name: k8s-logs-manager-role
  apiGroup: rbac.authorization.k8s.io
